# Generated by Django 5.1.3 on 2024-11-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
