# Generated by Django 5.1.3 on 2024-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assigned', 'Assigned Task'), ('re-assigned', 'Re-assigned Task'), ('task_due', 'Task Due')], max_length=20),
        ),
    ]
