# Generated by Django 5.1.3 on 2024-11-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_service', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
